global:
  scrape_interval: 15s

scrape_configs:
  - job_name: "flask_app"
    static_configs:
      - targets: ["unus-app:8080"]

  - job_name: "celery_worker"
    static_configs:
      - targets: ["celery-worker:5555"]  # Adjust to Celery's actual Prometheus port if different
