name: unus
services:
  - name: unus-web
    dockerfile_path: Dockerfile
    github:
      branch: main
      deploy_on_push: true
      repo: Junebugg1214/Unus1
    http_port: 8080
    instance_size_slug: basic-xxs
    instance_count: 1
    envs:
      - key: FLASK_ENV
        value: production
      - key: DATABASE_URL
        value: ${db.DATABASE_URL}  # Will be automatically populated by DigitalOcean
      - key: SECRET_KEY
        type: SECRET
        value: your-secret-key-here
    health_check:
      http_path: /health
      period_seconds: 30
      timeout_seconds: 4
      failure_threshold: 2
      success_threshold: 2

databases:
  - engine: PG
    name: unus-db
    production: true
