name: unus
databases:
 - engine: PG
   name: unus-db
   production: true
 - engine: REDIS
   name: unus-redis
   production: true

services:
 - name: backend
   image:
     registry_type: DOCKER_HUB
     registry: docker.io
     repository: mjsaintjour/unus-backend
     tag: latest
   source_dir: backend
   github:
     branch: main
     deploy_on_push: true
     repo: Junebugg1214/Unus
   http_port: 5000
   instance_size_slug: basic-xxs
   instance_count: 1
   routes:
     - path: /api
   envs:
     - key: FLASK_APP
       scope: RUN_TIME
       value: wsgi.py
     - key: FLASK_ENV
       scope: RUN_TIME
       value: production
     - key: DATABASE_URL
       scope: RUN_TIME
       value: ${unus-db.DATABASE_URL}
     - key: CELERY_BROKER_URL
       scope: RUN_TIME
       value: ${unus-redis.REDIS_URL}
     - key: CELERY_RESULT_BACKEND
       scope: RUN_TIME
       value: ${unus-redis.REDIS_URL}
     - key: SECRET_KEY
       scope: RUN_TIME
       type: SECRET
       value: ${_self.SECRET_KEY}
     - key: JWT_SECRET_KEY
       scope: RUN_TIME
       type: SECRET
       value: ${_self.JWT_SECRET_KEY}

 - name: frontend
   image:
     registry_type: DOCKER_HUB
     registry: docker.io
     repository: mjsaintjour/unus-frontend
     tag: latest
   source_dir: frontend
   github:
     branch: main
     deploy_on_push: true
     repo: Junebugg1214/Unus
   http_port: 80
   instance_size_slug: basic-xxs
   instance_count: 1
   routes:
     - path: /
   envs:
     - key: REACT_APP_API_URL
       scope: BUILD_TIME
       value: ${APP_URL}/api
     - key: NODE_ENV
       scope: BUILD_TIME
       value: production
   cors:
     allow_origins:
       - ${APP_URL}

 - name: celery-worker
   image:
     registry_type: DOCKER_HUB
     registry: docker.io
     repository: mjsaintjour/unus-backend
     tag: latest
   source_dir: backend
   github:
     branch: main
     deploy_on_push: true
     repo: Junebugg1214/Unus
   instance_count: 1
   instance_size_slug: basic-xxs
   run_command: celery -A app.celery worker --loglevel=info
   envs:
     - key: FLASK_ENV
       scope: RUN_TIME
       value: production
     - key: DATABASE_URL
       scope: RUN_TIME
       value: ${unus-db.DATABASE_URL}
     - key: CELERY_BROKER_URL
       scope: RUN_TIME
       value: ${unus-redis.REDIS_URL}
     - key: CELERY_RESULT_BACKEND
       scope: RUN_TIME
       value: ${unus-redis.REDIS_URL}
     - key: SECRET_KEY
       scope: RUN_TIME
       type: SECRET
       value: ${backend.SECRET_KEY}
     - key: JWT_SECRET_KEY
       scope: RUN_TIME
       type: SECRET
       value: ${backend.JWT_SECRET_KEY}

jobs:
 - name: migrate
   kind: PRE_DEPLOY
   git:
     repo_clone_url: https://github.com/Junebugg1214/Unus.git
     branch: main
   source_dir: backend
   environment_slug: python
   envs:
     - key: DATABASE_URL
       scope: RUN_TIME
       value: ${unus-db.DATABASE_URL}
   run_command: flask db upgrade